# -*- coding: utf-8 -*-
"""Energy demand forecatsing using Granite-Time Seeries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yR7XOFHbQltcxRXWTv9F4HwEnS0sZ-_B

TinyTimeMixers (TTMs) are compact pre-trained models for Multivariate Time-Series Forecasting, open-sourced by IBM Research. With less than 1 Million parameters, TTM outperforms several popular benchmarks in zero-shot and few-shot forecasting. In this recipe, we demonstrate few-shot fine-tuning on a real-world energy demand dataset from Spain.
"""

!pip install "granite_tsfm[notebooks]==0.2.23"

import math
import os
import numpy as np
import pandas as pd
import torch
from torch.optim import AdamW
from torch.optim.lr_scheduler import OneCycleLR
from transformers import EarlyStoppingCallback, Trainer, TrainingArguments, set_seed
from tsfm_public import (
    TimeSeriesForecastingPipeline,
    TimeSeriesPreprocessor,
    TinyTimeMixerForPrediction,
    TrackingCallback,
    count_parameters,
    get_datasets,
)
from tsfm_public.toolkit.time_series_preprocessor import prepare_data_splits
from tsfm_public.toolkit.visualization import plot_predictions

"""Configuration Variables"""

timestamp_column = "time"
target_columns = ["total load actual", "generation solar"]
TTM_MODEL_REVISION = "512-96-ft-r2.1"
context_length = 512
prediction_length = 96
fewshot_fraction = 0.05
OUT_DIR = "/tmp/ttm_results"
device = "cuda" if torch.cuda.is_available() else "cpu"

DATA_FILE_PATH = "hf://datasets/vitaliy-sharandin/energy-consumption-hourly-spain/energy_dataset.csv"
DATA_FILE_EXOG_PATH = "hf://datasets/vitaliy-sharandin/energy-consumption-weather-hourly-spain/weather_features.csv"

"""Filling missing values

"""

input_df = pd.read_csv(DATA_FILE_PATH, parse_dates=[timestamp_column])
input_df = input_df.ffill()

"""We also process and include exogenous weather data. We calculate a daily rolling average and then take the median across all cities to get a country-level forecast."""

exog_timestamp_column = "dt_iso"
exog_data = pd.read_csv(
    DATA_FILE_EXOG_PATH,
    parse_dates=[exog_timestamp_column],
)
keep_cols = [
    c for c in exog_data.columns if c not in ["weather_id", "weather_main", "weather_description", "weather_icon"]
]
exog_data = exog_data[keep_cols]
value_cols = [c for c in keep_cols if c not in ["dt_iso", "city_name"]]
city_data = []
for city in exog_data.city_name.unique():
    df = (
        exog_data[exog_data.city_name == city].set_index("dt_iso")[value_cols].rolling(window=24, min_periods=1).mean()
    )
    df["city_name"] = city
    df = df.reset_index()
    city_data.append(df)
exog_df = pd.concat(city_data, axis=0).sort_values(by="dt_iso")
exog_df = exog_df.groupby("dt_iso")[value_cols].median()

"""Now we join the target data with the exogenous data."""

input_df = input_df.merge(exog_df, left_on=timestamp_column, right_on=exog_timestamp_column)

for target_column in target_columns:
    input_df.plot(x=timestamp_column, y=target_column, figsize=(20, 3))

"""We define the control columns (features known in the future) and set up the time series preprocessor to split our data."""

split_config = {"train": 0.6, "test": 0.2}
column_specifiers = {
    "timestamp_column": timestamp_column,
    "id_columns": [],
    "target_columns": target_columns,
    "control_columns": [
        "temp",
        "temp_min",
        "temp_max",
        "pressure",
        "wind_speed",
        "wind_deg",
        "humidity",
        "rain_1h",
        "rain_3h",
        "clouds_all",
    ],
}
tsp = TimeSeriesPreprocessor(
    **column_specifiers,
    context_length=context_length,
    prediction_length=prediction_length,
    scaling=True,
    encode_categorical=False,
    scaler_type="standard",
)
train_df, valid_df, test_df = prepare_data_splits(input_df, context_length=context_length, split_config=split_config)

"""Fine-tuning the Model"""

set_seed(42)
finetune_forecast_model = TinyTimeMixerForPrediction.from_pretrained(
    "ibm-granite/granite-timeseries-ttm-r2",
    num_input_channels=tsp.num_input_channels,
    prediction_channel_indices=tsp.prediction_channel_indices,
    exogenous_channel_indices=tsp.exogenous_channel_indices,
    fcm_use_mixer=True,
    fcm_context_length=10,
    enable_forecast_channel_mixing=True,
    decoder_mode="mix_channel",
)

for param in finetune_forecast_model.backbone.parameters():
    param.requires_grad = False
train_dataset, valid_dataset, test_dataset = get_datasets(
    tsp,
    input_df,
    split_config,
    fewshot_fraction=fewshot_fraction,
    fewshot_location="first",
    use_frequency_token=finetune_forecast_model.config.resolution_prefix_tuning,
)

"""Now we set up the training arguments, optimizer, and scheduler using the Hugging Face Trainer."""

learning_rate: float = 0.0004
num_epochs: int = 200
patience: int = 10
batch_size: int = 256

finetune_forecast_args = TrainingArguments(
    output_dir=os.path.join(OUT_DIR, "output"),
    overwrite_output_dir=True,
    learning_rate=learning_rate,
    num_train_epochs=num_epochs,
    do_eval=True,
    eval_strategy="epoch",
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    dataloader_num_workers=4,
    report_to=None,
    save_strategy="epoch",
    logging_strategy="epoch",
    save_total_limit=1,
    logging_dir=os.path.join(OUT_DIR, "logs"),
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    use_cpu=device != "cuda",
)

early_stopping_callback = EarlyStoppingCallback(
    early_stopping_patience=patience,
    early_stopping_threshold=0.00001,
)
tracking_callback = TrackingCallback()

optimizer = AdamW(finetune_forecast_model.parameters(), lr=learning_rate)
scheduler = OneCycleLR(
    optimizer,
    learning_rate,
    epochs=num_epochs,
    steps_per_epoch=math.ceil(len(train_dataset) / (batch_size)),
)

finetune_forecast_trainer = Trainer(
    model=finetune_forecast_model,
    args=finetune_forecast_args,
    train_dataset=train_dataset,
    eval_dataset=valid_dataset,
    callbacks=[early_stopping_callback, tracking_callback],
    optimizers=(optimizer, scheduler),
)

"""start the training process on 5% of the data"""

finetune_forecast_trainer.train()

"""Evaluate the Model"""

pipeline = TimeSeriesForecastingPipeline(
    finetune_forecast_model,
    device=device,
    feature_extractor=tsp,
    batch_size=batch_size,
)
finetune_forecast = pipeline(test_df)

def custom_metric(actual, prediction, column_header="results"):
    a = np.asarray(actual.tolist())
    p = np.asarray(prediction.tolist())
    mask = ~np.any(np.isnan(a), axis=1)
    mse = np.mean(np.square(a[mask, :] - p[mask, :]))
    mae = np.mean(np.abs(a[mask, :] - p[mask, :]))
    return pd.DataFrame(
        {
            column_header: {
                "mean_squared_error": mse,
                "root_mean_squared_error": np.sqrt(mse),
                "mean_absolute_error": mae,
            }
        }
    )

custom_metric(
    finetune_forecast["total load actual"],
    finetune_forecast["total load actual_prediction"],
    "fine-tune forecast (total load)",
)

"""we can plot the predictions against the actual values for some random samples from our test set."""

plot_predictions(
    input_df=test_df,
    predictions_df=finetune_forecast,
    timestamp_column=timestamp_column,
    freq=tsp.freq,
    plot_dir=None,
    plot_prefix="Test",
    channel="generation solar",
    plot_context=2 * prediction_length,
    indices=[2464, 3651, 4964, 6224],
    num_plots=4,
)

plot_predictions(
    input_df=test_df,
    predictions_df=finetune_forecast,
    timestamp_column=timestamp_column,
    freq=tsp.freq,
    plot_dir=None,
    plot_prefix="Test",
    channel="total load actual",
    plot_context=2 * prediction_length,
    indices=[5352, 4964, 1451, 6691],
    num_plots=4,
)

"""Making a Forecast
To simulate a real-world scenario, we use historical data and known future control variables to predict the next period
"""

historical_df = input_df.iloc[-context_length - prediction_length : -prediction_length].copy()
controls_df = input_df.iloc[-prediction_length:][column_specifiers["control_columns"]].copy()

pipeline = TimeSeriesForecastingPipeline(
    finetune_forecast_trainer.model,
    feature_extractor=tsp,
    device=device,
)

future_forecast = pipeline(historical_df, future_time_series=controls_df)

historical_df[timestamp_column] = pd.to_datetime(historical_df[timestamp_column])

plot_predictions(
    input_df=historical_df,
    predictions_df=future_forecast,
    freq=tsp.freq,
    timestamp_column=timestamp_column,
    channel=target_columns[0],
)
plot_predictions(
    input_df=historical_df,
    predictions_df=future_forecast,
    freq=tsp.freq,
    timestamp_column=timestamp_column,
    channel=target_columns[1],
)